language: python

python:
    - 2.7

install:
    - pip install -r dev_requirements.txt
    - pip install -r requirements.txt
    - pip install coveralls
    - pip freeze

script:
    - make lint
    - make docbook
    - make coverage

after_script:
    - coveralls
