version: '2'
services: 
    otter: 
        image: otter:latest 
        ports:
            - "9000:9000"
        depends_on:
            - mimic
            - db
            - zk
        environment:
            IDENTITY_URL: "http://mimic:8900/identity/v2.0"
            CASS_HOSTS: "tcp:db:9160"
            ZK_HOSTS: "zk:2181"
            URL_ROOT: "http://otter:9000"
            BOOTSTRAP: "yes"
        volumes:
            - ./otter:/app/otter
            - ./scripts:/app/scripts
            - ./twisted:/app/twisted
    db:
        image: cassandra:latest
    zk:
        image: zookeeper:latest
        ports:
            - "2181:2181"
    mimic: 
        image: mimic:latest
        command: twistd -n mimic --realtime --verbose
    cafe:
        image: cafe:latest
        environment:
            - OTTER_ROOT=http://otter:9000
            - IDENTITY_ROOT=http://mimic:8900
            - WAIT=yes
        volumes:
            - ./autoscale_cloudroast/test_repo:/cafe/autoscale_cloudroast/test_repo
            - ./autoscale_cloudcafe/autoscale_fixtures:/cafe/autoscale_cloudcafe/autoscale_fixtures
            - ./_docker_cafe_logs:/root/.cloudcafe/logs/autoscale
        command:
            dev-convergence -p functional
        depends_on:
            - otter
            - mimic
    trial:
        image: otter:latest 
        volumes:
            - ./otter:/app/otter
            - ./_docker_trial_tmp:/tmp
        environment:
            - AS_USERNAME=jenkins_user
            - AS_PASSWORD=jenkins_password
            - AS_IDENTITY=http://mimic:8900/identity/v2.0
            - AS_FLAVOR_REF=2
            - AS_REGION=ORD
            - AS_CONVERGENCE_TENANT=000001
            - AS_CONVERGENCE_TENANT_FOR_AUTH_ERRORS=000010
            - AS_AUTOSCALE_LOCAL_URL=http://otter:9000/v1.0/{0}
            - AS_NOVA_SC_KEY=cloudServersOpenStack
            - AS_CLB_SC_KEY=cloudLoadBalancers
            - AS_USING_MIMIC=yes
            - AS_SELFHEAL_INTERVAL=20
        command:
            # We have -z 1 here to randomize the order (with a seed of positive
            # integer 1). In this case, if you run "trial" by itself it tends to
            # freeze up mimic pretty hard. It works fine running it along side
            # the 'cafe' tests and just letting everything go with
            # 'docker-compose up'. It also works fine if you randomize the
            # tests.
            # 
            # Admittedly, I had to raise pyOpenSSL version to 16.2.0 from 16.0.0
            # and crytography to 1.9 from 1.4 to get the Dockerfile to work.
            # Also, I use a version 246 commits behind, to match the version we
            # originally had here.
            # 
            # I think this probably means we have some mimic bug, but we lost
            # the last mimic developer sometime around July, 2018, and I haven't
            # tried a newer version yet. This will work for now.
            dockerize -timeout 60s -wait http://otter:9000/health -wait http://mimic:8900
                trial -z 1 -j10 --temp-directory=/tmp/_trial_temp otter.integration.tests
        depends_on:
            - otter
            - mimic
