version: '2'
services: 
    otter: 
        build: .
        ports:
            - "9000:9000"
        links:
            - mimic
            - db
            - zk
        environment:
            IDENTITY_URL: "http://mimic:8900/v2.0"
            CASS_HOSTS: "tcp:db:9160"
            ZK_HOSTS: "zk:2181"
            BOOTSTRAP: "yes"
    db:
        image: cassandra:2.1
    zk:
        image: zookeeper:latest
    mimic: 
        build: mimic/
